export const PERMISSIONS = {
  ADMIN_MANAGEMENT: {
    READ: "AM:READ",
    CREATE: "AM:CREATE",
    UPDATE: "AM:UPDATE",
    DELETE: "AM:DELETE",
  },
  USER_MANAGEMENT: {
    READ: "UM:READ",
    CREATE: "UM:CREATE",
    UPDATE: "UM:UPDATE",
    DELETE: "UM:DELETE",
  },
  CHAT: {
    READ: "CHAT:READ",
    CREATE: "CHAT:CREATE",
    UPDATE: "CHAT:UPDATE",
    DELETE: "CHAT:DELETE",
  },
  MENU: {
    READ: "MENU:READ",
    CREATE: "MENU:CREATE",
    UPDATE: "MENU:UPDATE",
    DELETE: "MENU:DELETE",
  },
  ORDER: {
    READ: "ORDER:READ",
    CREATE: "ORDER:CREATE",
    UPDATE: "ORDER:UPDATE",
    DELETE: "ORDER:DELETE",
  },
  DRIVER_PROFILE: {
    READ: "DRIVER_PROFILE:READ",
    CREATE: "DRIVER_PROFILE:CREATE",
    UPDATE: "DRIVER_PROFILE:UPDATE",
    DELETE: "DRIVER_PROFILE:DELETE",
  },
  RESTAURANT_PROFILE: {
    READ: "RESTAURANT_PROFILE:READ",
    CREATE: "RESTAURANT_PROFILE:CREATE",
    UPDATE: "RESTAURANT_PROFILE:UPDATE",
    DELETE: "RESTAURANT_PROFILE:DELETE",
  },
} as const;

export const ROLES = {
  ADMIN: "ADMIN",
} as const;
